### PR TITLE
worker: Expose safety worker queue size config

### LINKED ISSUE #19: Bug: Sporadic 'Panicked with Cannot push to safety queue anymore, overflow!'
Original report: https://github.com/qorix-group/inc_orchestrator_internal/issues/396
----

### Describe the bug:
Sporadically `Panicked with Cannot push to safety queue anymore, overflow!` happens in the test where a lot failures are designated for the safety worker. Runtime's task_queue_size increase seems to not fix or improve the rate.

Test spawns in a loop:
1. Regular tasks, that inside makes a safe spawn of the OK task
2. Regular tasks, that inside makes a safe spawn of the Err task

It is expected that Err tasks are handled in the safety worker.

### Steps to reproduce the behavior:
1. `git checkout igorostrowskiq_safety_worker_tests`
2. `cd component_integration_tests/rust_test_scenarios`
3. `RUST_BACKTRACE=1 cargo run -- --name runtime.worker.safety_worker.heavy_load --input '{"runtime": {"task_queue_size": 4096, "workers": 4, "safety_worker": {}}, "test": {"successful_tasks": 600, "failing_tasks": 300}}'`
4. Rerun the command multiple times

### Observed behavior:
"Currently no custom handler connected for panic, using rust one. Panicked with Cannot push to safety queue anymore, overflow!
fatal runtime error: failed to initiate panic, error 5"

### Expected behavior
No panic

### Occurrence:
Sporadic (0,1%-2% on my machine, much higher on other machine)

### Attachments / Logs:
[log.txt](https://github.com/user-attachments/files/23603599/log.txt)

### PR DESCRIPTION
**Pull request by prabakaranklst**
Expose safety worker task queue size configuration to user.

## Pre-Review Checklist for the PR Author

* [x] PR title is short, expressive and meaningful
* [x] Commits are properly organized
* [x] Relevant issues are linked in the [References](#references) section
* [x] Tests are conducted
* [ ] Unit tests are added

## Checklist for the PR Reviewer

* [ ] Commits are properly organized and messages are according to the guideline
* [ ] Unit tests have been written for new behavior
* [ ] Public API is documented
* [ ] PR title describes the changes

## Post-review Checklist for the PR Author

* [ ] All open points are addressed and tracked via issues

## References

Closes #19

### CODE REVIEW

File: src/kyron-macros/src/lib.rs [hunk 1]
```diff
@@ -324,6 +331,18 @@ pub fn main(attr: TokenStream, item: TokenStream) -> TokenStream {
...
+            Some(e) => {
+                let queue_size = expr_to_usize(&e).unwrap();
+                if !queue_size.is_power_of_two() {
+                    return syn::Error::new_spanned(e, "'safety_worker_task_queue_size' must be a power of two.")
+                        .to_compile_error()
+                        .into();
+                }
+                quote! { #e }
+            }
+            None => quote! { 64 }, // default
```
[the remark this answers is not in the document]
Comment (pawelrutkaq) [reply src/kyron-macros/src/lib.rs]: as before SAFETY_QUEUE_SIZE

**Review by pawelrutkaq — COMMENTED** [review]
and i did not spot adaptations for failing tests as in ticket? why is that ?

File: src/kyron-macros/src/lib.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (prabakaranklst) [reply src/kyron-macros/src/lib.rs]: Not fixed to avoid circular dependency because `kyron` has dependency on `kyron-macros`. 
**Note:**
If SAFETY_QUEUE_SIZE is defined in `kyron` and if this dependency is added in `kyron-macros`, it results in circular dependency.

File: tests/test_cases/tests/runtime/worker/test_safety_worker.py [hunk 2]
```diff
@@ -330,7 +331,11 @@ def test_config(self, successful_task_count: int, fail_task_count: int) -> dict[
             "runtime": {
                 "task_queue_size": 2048,
                 "workers": 4,
-                "safety_worker": {},
+                "safety_worker": {
+                    "thread_priority": 50,
+                    "thread_scheduler": "fifo",
```
Comment (PiotrKorkus) [inline tests/test_cases/tests/runtime/worker/test_safety_worker.py]: is it needed? I believe test should pass without root privileges and setting thread params

Comment (prabakaranklst) [reply tests/test_cases/tests/runtime/worker/test_safety_worker.py]: You are right, but with increased queue size of 512 for 300-failing tasks.
The typical real-world application would be with appropriate higher priority for safety thread, so I configured it.

Comment (PiotrKorkus) [reply tests/test_cases/tests/runtime/worker/test_safety_worker.py]: I would say it would be better to increase safety queue then and remove thread params. I understand the idea behind real-world examples but I would rather keep to what is possible to do in components integration tests and leave typical usages to feature integration tests in reference_integration.

**Review by PiotrKorkus — APPROVED** [review]

**Review by pawelrutkaq — APPROVED** [review]
